# Generated by Django 2.0 on 2017-12-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='choice_text',
            new_name='image_url',
        ),
    ]
